DROP TABLE IF EXISTS "artists";
CREATE TABLE "artists" ("id" INTEGER PRIMARY KEY  NOT NULL , "artist" VARCHAR);
INSERT INTO "artists" VALUES(1,'Lady Gaga');
INSERT INTO "artists" VALUES(3,'Carrie Underwood');
INSERT INTO "artists" VALUES(4,'Periphery');
INSERT INTO "artists" VALUES(5,'John Mayer');
INSERT INTO "artists" VALUES(6,'John McCarthy');
INSERT INTO "artists" VALUES(7,'John Lennon');
INSERT INTO "artists" VALUES(8,'Black Eye Peas');
INSERT INTO "artists" VALUES(9,'Black Sabbath');
INSERT INTO "artists" VALUES(10,'Blackmill');
INSERT INTO "artists" VALUES(11,'Britney Spears');
INSERT INTO "artists" VALUES(12,'Lady Gaga');
INSERT INTO "artists" VALUES(13,'Carrie Underwood');
INSERT INTO "artists" VALUES(14,'Periphery');
INSERT INTO "artists" VALUES(15,'John Mayer');
INSERT INTO "artists" VALUES(16,'John McCarthy');
INSERT INTO "artists" VALUES(17,'John Lennon');
INSERT INTO "artists" VALUES(18,'Black Eye Peas');
INSERT INTO "artists" VALUES(19,'Black Sabbath');
INSERT INTO "artists" VALUES(20,'Blackmill');
INSERT INTO "artists" VALUES(21,'Britney Spears');
INSERT INTO "artists" VALUES(22,'Ariana Grande');
INSERT INTO "artists" VALUES(23,'Underoath');
INSERT INTO "artists" VALUES(24,'Selena Gomes');
INSERT INTO "artists" VALUES(25,'Killswitch Engage');
INSERT INTO "artists" VALUES(26,'Madonna');
INSERT INTO "artists" VALUES(27,'Wiz Khalifa');
INSERT INTO "artists" VALUES(28,'Kendrick Lamar');
INSERT INTO "artists" VALUES(29,'Justin Bieber');
INSERT INTO "artists" VALUES(30,'Justin Timberlake');
INSERT INTO "artists" VALUES(31,'One Direction');
INSERT INTO "artists" VALUES(32,'Jennifer Lopez');
